In [1]:
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

sys.path.insert(0, '../../utils')
np.set_printoptions(precision = 2)

### Preprocess data

In [3]:
from ipynb.fs.defs.data_preprocessing import preprocess_dataset

X_train, X_test, y_train, y_test = preprocess_dataset(
    dataset_url = '50_Startups.csv', 
    nominal_feature_cols = [3], 
    debug = True
)


X_train
 [[1.0 0.0 55493.95 103057.49 214634.81]
 [0.0 1.0 46014.02 85047.44 205517.64]
 [1.0 0.0 75328.87 144135.98 134050.07]
 [0.0 0.0 46426.07 157693.92 210797.67]
 [1.0 0.0 91749.16 114175.79 294919.57]
 [1.0 0.0 130298.13 145530.06 323876.68]
 [1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 1.0 1000.23 124153.04 1903.93]
 [0.0 1.0 542.05 51743.15 0.0]
 [0.0 1.0 65605.48 153032.06 107138.38]
 [0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 61994.48 115641.28 91131.24]
 [0.0 0.0 63408.86 129219.61 46085.25]
 [0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 23640.93 96189.63 148001.11]
 [0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 1.0 15505.73 127382.3 35534.17]
 [0.0 1.0 120542.52 148718.95 311613.29]
 [0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 0.0 64664.71 139553.16 137962.62]
 [0.0 1.0 131876.9 99814.71 362861.36]
 [0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 0.0 28754.33 118546.05 172795.67]
 [0.0 0.0 0.0 116983.8 45173.06]
 [0.0 0.0 162597.7 151377.59 443898.53]
 [1.0 0.0 938

### Train the Multiple Linear Regression model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

In [ ]:
print(model.coef_, model.intercept_)

### Predict the Test set results

In [ ]:
# UTIL
def concatenate_vecs_vertically(*vecs):
    VERTICAL_AXIS = 1
    vertical_vecs = []
    verticalize = lambda vec : vec.reshape(len(vec), VERTICAL_AXIS)
    for vec in vecs:
        vertical_vecs.append(verticalize(vec))
        
    return np.concatenate(tuple(vertical_vecs), VERTICAL_AXIS)

In [4]:
y_predict = model.predict(X_test)
print('Predicted data vs. Real data')
print(concatenate_vecs_vertically(y_predict, y_test))

NameError: name 'model' is not defined